# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Things Network
description: > # this means to ignore newlines until "baseurl:"
  We are building a global open free crowdsourced long range low power IoT
  data network.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://www.thethingsnetwork.org" # the base hostname & protocol for your site
twitter:
  username: thethingsnetwrk
facebook:
  publisher: https://www.facebook.com/thethingsnetwork
github:
  repository_url: https://github.com/TheThingsNetwork/docs
logo: /assets/images/the-things-white.png

# Build settings
collections:
  content:
    output: true
    permalink: /:path:output_ext
defaults:
  - 
    scope:
      path: ""
      type: content
    values:
      layout: page
      image: /assets/images/the-things-white.png
markdown: kramdown
lsi: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
compress_html:
  blanklines: true

# Exclude vendor which Travis will add
exclude: [ node_modules, vendor, Rakefile, Gemfile, Gemfile.lock, gulpfile.js, "npm-debug.*", package.json, Rakefile, README.md, webpack.config.js ]