# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Things Network
description: > # this means to ignore newlines until "baseurl:"
  We are building a global open free crowdsourced long range low battery IoT
  data network.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://www.thethingsnetwork.org" # the base hostname & protocol for your site
repository: TheThingsNetwork/docs
twitter:
  username: thethingsnetwrk
facebook:
  publisher: https://www.facebook.com/thethingsnetwork
logo: /assets/images/the-things-white.png

# Variables
var:
  current: "v1-staging"

# Build settings
collections:
  includes:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/the-things-white.png
  - scope:
      path: ""
      type: includes
    values:
      layout: guide
markdown: kramdown
# Exclude vendor which Travis will add
exclude: [ node_modules, vendor, Gemfile, Gemfile.lock, gulpfile.js, "npm-debug.*", package.json, Rakefile, README.md, test, webpack.config.js, yarn.lock ]
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from

# Use GitHub.io overrides local as well
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
